### PR TITLE
Slack naming

### PR DESCRIPTION
**Pull request by langdon**

### CODE REVIEW

**Comment by IanSaucy** [comment]
Looks fine but your examples don't align with your definitions. For example you said season should be `s, f, su` but your examples use `SP, FA`. I feel like the season should be the same as the short name used for classes so `SP, FA` and whatever summer is -- I think it's `SUM`

**Comment by langdon** [comment]
> Looks fine but your examples don't align with your definitions. For example you said season should be `s, f, su` but your examples use `SP, FA`. I feel like the season should be the same as the short name used for classes so `SP, FA` and whatever summer is -- I think it's `SUM`

incorporated your ideas and fixed examples

**Comment by IanSaucy** [comment]
lgtm

**Comment by mvoong18** [comment]
looks good

**Pull request merged**
