### PR TITLE
incorporating DS/ML requests

### PR DESCRIPTION
**Pull request by langdon**
1. removed heroku 
2. added more detail on scc
3. added DS/ML requests model

### CODE REVIEW

**Comment by langdon** [comment]
@IanSaucy @mvoong18 and another one :)

**Comment by mvoong18** [comment]
Our emails are missing in the second bullet for SE requests and for DS/ML requests. Otherwise looks good

**Comment by mvoong18** [comment]
looks good

**Comment by langdon** [comment]
> Our emails are missing in the second bullet for SE requests and for DS/ML requests. Otherwise looks good

vagaries of markdown rendering.. i put angle brackets around them and jekyll decided to hide them

**Review by IanSaucy — APPROVED** [review]
lgtm

**Pull request merged**
