### PR TITLE
Added project structuring guide, project outline templates

### PR DESCRIPTION
**Pull request by oindrillac**
Adding resources from ML practicum on project structuring guide, project outline templates for the larger Spark group to utilize.

Please take a look @langdon @IanSaucy @mvoong18 and please suggest any changes.

### CODE REVIEW

**Comment by langdon** [comment]
@oindrillac could you rejigger this a bit to be "DS/ML Projects" like just scope it to that space? I think the SE one will be very similar but I think we may want them to be able to diverge a bit over time.

**Comment by oindrillac** [comment]
oh yes, happy to do that. Will align these with https://github.com/BU-Spark/ml-549-course/blob/main/project-structure/project-structure.md

**Comment by IanSaucy** [comment]
Leaving the content part to Langdon but we need to add some special things to the markdown to support Jekyll. 

You'll need to add something along the lines of the following to each markdown file so that it generates a page on the final website:

```
---
layout: default
title: Project Documentation Guidelines
nav_order: 1
---
``` 

Here is the framework we're using if you want to use anything specific from it: https://just-the-docs.github.io/just-the-docs/

**Comment by IanSaucy** [comment]
bump (:

**Pull request merged**
